In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
# TODO: 데이터 불러와서 확인하기
rocket = pd.read_csv('data/RocketLaunchDataCSV.csv')

In [4]:
rocket.head()

,Name,Date,Time (East Coast),Location,Crewed or Uncrewed,Launched?,High Temp,Low Temp,Ave Temp,Temp at Launch Time,...,Max Wind Speed,Visibility,Wind Speed at Launch Time,Hist Ave Max Wind Speed,Hist Ave Visibility,Sea Level Pressure,Hist Ave Sea Level Pressure,Day Length,Condition,Notes
0,NaN,04-Dec-58,NaN,Cape Canaveral,NaN,NaN,75.0,68.0,71.00,NaN,...,16.0,15.0,NaN,NaN,NaN,30.22,NaN,10:26,Cloudy,NaN
1,NaN,05-Dec-58,NaN,Cape Canaveral,NaN,NaN,78.0,70.0,73.39,NaN,...,14.0,10.0,NaN,NaN,NaN,30.2,NaN,10:26,Cloudy,NaN
2,Pioneer 3,06-Dec-58,1:45,Cape Canaveral,Uncrewed,Y,73.0,0.0,60.21,62.0,...,15.0,10.0,11.0,NaN,NaN,30.25,NaN,10:25,Cloudy,NaN
3,NaN,07-Dec-58,NaN,Cape Canaveral,NaN,NaN,76.0,57.0,66.04,NaN,...,10.0,10.0,NaN,NaN,NaN,30.28,NaN,10:25,Partly Cloudy,NaN
4,NaN,08-Dec-58,NaN,Cape Canaveral,NaN,NaN,79.0,60.0,70.52,NaN,...,12.0,10.0,NaN,NaN,NaN,30.23,NaN,12:24,Partly Cloudy,NaN

In [5]:
rocket.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          60 non-null     str
 1   Date                          300 non-null    str
 2   Time (East Coast)             59 non-null     str
 3   Location                      300 non-null    str
 4   Crewed or Uncrewed            60 non-null     str
 5   Launched?                     60 non-null     str
 6   High Temp                     299 non-null    float64
 7   Low Temp                      299 non-null    float64
 8   Ave Temp                      299 non-null    float64
 9   Temp at Launch Time           59 non-null     float64
 10  Hist High Temp                299 non-null    float64
 11  Hist Low Temp                 299 non-null    float64
 12  Hist Ave Temp                 299 non-null    float64
 13  Percipitation at Launch Time  299 non-null    float64
 14  Hist Ave Percipitation        299 non-null    float64
 15  Wind Direction                299 non-null    str
 16  Max Wind Speed                299 non-null    float64
 17  Visibility                    299 non-null    float64
 18  Wind Speed at Launch Time     59 non-null     float64
 19  Hist Ave Max Wind Speed       0 non-null      float64
 20  Hist Ave Visibility           0 non-null      float64
 21  Sea Level Pressure            299 non-null    str
 22  Hist Ave Sea Level Pressure   0 non-null      float64
 23  Day Length                    298 non-null    str
 24  Condition                     298 non-null    str
 25  Notes                         3 non-null      str
dtypes: float64(15), str(11)
memory usage: 74.7 KB

In [ ]:
# TODO: 결측치 처리및 문자열데이터 인코딩

In [7]:
# 전체가 누락된 컬럼 : 'Hist Ave Max Wind Speed','Hist Ave Visibility','Hist Ave Sea Level Pressure'
# 날씨와 무관한 컬럼 : 'Name','Date',Time (East Coast)','Location','Day Length','Notes', 'Sea Level Pressure'
# 종속변수 : 'Launched?'

drop_cols = ['Hist Ave Max Wind Speed','Hist Ave Visibility','Hist Ave Sea Level Pressure', 'Name','Date','Time (East Coast)','Location','Day Length','Notes', 'Sea Level Pressure']

rocket = rocket.drop(drop_cols, axis=1)

In [11]:
# 종속변수의 null 처리 : NaN -> 'N'
rocket['Launched?'] = rocket['Launched?'].fillna('N')

In [14]:
rocket['Launched?'] = rocket['Launched?'].map({'Y':1,'N':0 })

In [21]:
# 적당한 값으로 결측치 처리
# crewed = Uncrewed로
# Launche? = N
# Wind Direction = Unknown
# Condition = Cloudy
# 기타는 중앙값 또는 최빈값
rocket['Crewed or Uncrewed'] = rocket['Crewed or Uncrewed'].fillna('Uncrewed')
rocket['Wind Direction'] = rocket['Wind Direction'].fillna('Unknown')
rocket['Condition'] = rocket['Condition'].fillna('Unknown')

In [22]:
rocket['Condition'].value_counts()

Condition
Cloudy            113
Partly Cloudy      68
Fair               68
Rain               24
T-Storm            12
Thunder             7
Mostly Cloudy       2
Unknown             2
Windy               1
Partly Cloudly      1
Light Rain          1
Heavy T-Storm       1
Name: count, dtype: int64

In [24]:
rocket.describe()

,Launched?,High Temp,Low Temp,Ave Temp,Temp at Launch Time,Hist High Temp,Hist Low Temp,Hist Ave Temp,Percipitation at Launch Time,Hist Ave Percipitation,Max Wind Speed,Visibility,Wind Speed at Launch Time
count,300.000000,299.000000,299.000000,299.000000,59.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,59.000000
mean,0.196667,81.394649,38.745819,69.747124,75.101695,81.852843,62.872910,72.389900,0.063043,0.413478,16.842809,12.929766,10.593220
std,0.398142,9.026700,33.423090,10.867407,10.471134,6.860432,8.806109,7.825282,0.211995,4.676693,4.701710,6.044445,4.672438
min,0.000000,51.000000,0.000000,29.040000,50.000000,71.000000,49.000000,60.000000,0.000000,0.060000,8.000000,7.000000,2.000000
25%,0.000000,77.000000,0.000000,63.050000,70.000000,75.000000,55.000000,65.000000,0.000000,0.080000,14.000000,10.000000,7.000000
50%,0.000000,82.000000,51.000000,71.610000,77.000000,82.000000,64.000000,72.000000,0.000000,0.110000,16.000000,10.000000,10.000000
75%,0.000000,88.000000,72.000000,78.530000,81.500000,88.000000,73.000000,80.000000,0.000000,0.200000,18.000000,15.000000,12.500000
max,1.000000,99.000000,83.000000,90.790000,98.000000,91.000000,79.000000,82.000000,1.800000,81.000000,60.000000,80.000000,26.000000

In [34]:
rocket.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Crewed or Uncrewed            300 non-null    int64
 1   Launched?                     300 non-null    int64
 2   High Temp                     300 non-null    float64
 3   Low Temp                      300 non-null    float64
 4   Ave Temp                      300 non-null    float64
 5   Temp at Launch Time           300 non-null    float64
 6   Hist High Temp                300 non-null    float64
 7   Hist Low Temp                 300 non-null    float64
 8   Hist Ave Temp                 300 non-null    float64
 9   Percipitation at Launch Time  300 non-null    float64
 10  Hist Ave Percipitation        300 non-null    float64
 11  Wind Direction                300 non-null    int64
 12  Max Wind Speed                300 non-null    float64
 13  Visibility                    300 non-null    float64
 14  Wind Speed at Launch Time     300 non-null    float64
 15  Condition                     300 non-null    int64
dtypes: float64(12), int64(4)
memory usage: 37.6 KB

In [27]:
numerical_cols = rocket.select_dtypes(include=['float64']).columns

In [28]:
numerical_cols

Index(['High Temp', 'Low Temp', 'Ave Temp', 'Temp at Launch Time',
       'Hist High Temp', 'Hist Low Temp', 'Hist Ave Temp',
       'Percipitation at Launch Time', 'Hist Ave Percipitation',
       'Max Wind Speed', 'Visibility', 'Wind Speed at Launch Time'],
      dtype='str')

In [29]:
rocket['High Temp'].fillna(rocket['High Temp'].median())

0      75.0
1      78.0
2      73.0
3      76.0
4      79.0
       ...
295    87.0
296    86.0
297    87.0
298    87.0
299    85.0
Name: High Temp, Length: 300, dtype: float64

In [30]:
for col in numerical_cols:
    rocket[col] = rocket[col].fillna(rocket[col].median())

In [32]:
# 문자데이터 인코딩
categorical_cols = ['Crewed or Uncrewed', 'Wind Direction', 'Condition']

In [33]:
from sklearn.preprocessing import LabelEncoder
for col in categorical_cols:
    le = LabelEncoder()
    rocket[col] = le.fit_transform(rocket[col])

In [35]:
rocket.sample(5)

,Crewed or Uncrewed,Launched?,High Temp,Low Temp,Ave Temp,Temp at Launch Time,Hist High Temp,Hist Low Temp,Hist Ave Temp,Percipitation at Launch Time,Hist Ave Percipitation,Wind Direction,Max Wind Speed,Visibility,Wind Speed at Launch Time,Condition
52,1,1,71.0,0.0,51.24,68.0,77.0,56.0,67.0,0.03,0.11,2,23.0,15.0,12.0,0
221,1,0,81.0,64.0,71.61,77.0,85.0,70.0,78.0,0.00,0.18,2,16.0,15.0,10.0,1
112,1,1,75.0,59.0,67.96,73.0,71.0,50.0,60.0,0.00,0.07,6,21.0,10.0,7.0,0
185,1,0,85.0,0.0,49.63,77.0,89.0,73.0,81.0,0.00,0.27,5,20.0,7.0,10.0,0
204,1,0,84.0,77.0,79.23,77.0,80.0,59.0,69.0,0.05,0.08,5,19.0,15.0,10.0,0

In [36]:
# TODO: 데이터 분리하기
X = rocket.drop(columns=['Launched?'])
y = rocket['Launched?']

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# 학습용 데이터와 테스트용 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97        48
           1       0.85      0.92      0.88        12

    accuracy                           0.95        60
   macro avg       0.91      0.94      0.92        60
weighted avg       0.95      0.95      0.95        60

In [40]:
model.get_depth()

6

In [ ]:
class DecisionTreeClassifier(
    *,
    criterion: Literal['gini', 'entropy', 'log_loss'] = "gini", 
    splitter: Literal['best', 'random'] = "best",
    max_depth: Int | None = None,  ##
    min_samples_split: float = 2, ##
    min_samples_leaf: float = 1, ##
    min_weight_fraction_leaf: Float = 0,
    max_features: float | Literal['auto', 'sqrt', 'log2'] | None = None,
    random_state: Int | RandomState | None = None,
    max_leaf_nodes: Int | None = None,
    min_impurity_decrease: Float = 0,
    class_weight: Mapping | str | Sequence[Mapping] | None = None,
    ccp_alpha: float = 0
)

In [ ]:
max_depth: Int | None = None,  ##  None,2, 3, 5, 7, 9
min_samples_split: float = 2, ## 2, 3, 4, 5
min_samples_leaf: float = 1, ## 1, 2, 3, 4

In [ ]:
# 도전미션: 최적의 파이미터 조건과 스코어 확인 GridSearchCV

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model_dt = DecisionTreeClassifier(random_state=42)

parameters = {'max_depth':[2, 3, 5, 6, 7, 8,9],
              'min_samples_split':[2, 3, 4, 5],
              'min_samples_leaf': [1, 2, 3, 4]}

dt = GridSearchCV(model_dt, param_grid=parameters, cv=skf, refit=True)

dt.fit(X_train, y_train)

print('best_params:', dt.best_params_)
print('best_score:', dt.best_score_)

best_model_dt = dt.best_estimator_
pred_dt = best_model_dt.predict(X_test)
print(classification_report(y_test, pred_dt))

best_params: {'max_depth': 2, 'min_samples_leaf': 1, 'min_samples_split': 2}
best_score: 0.9875
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        48
           1       1.00      0.92      0.96        12

    accuracy                           0.98        60
   macro avg       0.99      0.96      0.97        60
weighted avg       0.98      0.98      0.98        60

In [50]:
print(f'Train score: {dt.score(X_train, y_train): .4f}')
print(f'Test score: {dt.score(X_test, y_test): .4f}')

Train score:  0.9792
Test score:  0.9833

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model_rf = RandomForestClassifier(random_state=42)

parameters = { 'n_estimators': [100, 200, 300],
                'max_depth':[2, 3, 4, 5, 6],
                'min_samples_split':[2, 3, 4, 5]
              }

# n_jobs=-1
rf = GridSearchCV(model_rf, param_grid=parameters, cv=skf, refit=True)

rf.fit(X_train, y_train)

print('best_params:', rf.best_params_)
print('best_score:', rf.best_score_)

best_model_rf = rf.best_estimator_
pred_rf = best_model_rf.predict(X_test)
print(classification_report(y_test, pred_rf))

best_params: {'max_depth': 5, 'min_samples_split': 3, 'n_estimators': 200}
best_score: 0.9791666666666666
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        48
           1       1.00      0.92      0.96        12

    accuracy                           0.98        60
   macro avg       0.99      0.96      0.97        60
weighted avg       0.98      0.98      0.98        60

In [54]:
print(f'Train score: {rf.score(X_train, y_train): .4f}')
print(f'Test score: {rf.score(X_test, y_test): .4f}')

Train score:  0.9958
Test score:  0.9833

In [55]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

categorical_cols = ['Crewed or Uncrewed', 'Wind Direction', 'Condition']
X_encoded = pd.get_dummies(X, columns=categorical_cols)

# 학습용 데이터와 테스트용 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42, stratify=y)

# 스케일링 추가하기
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

model_knn = KNeighborsClassifier()

parameters = { 'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
'weights': ['uniform', 'distance'],
'metric': [ 'euclidean', 'manhattan', 'minkowski']
              }

# n_jobs=-1
knn = GridSearchCV(model_knn, param_grid=parameters, cv=skf, refit=True)

knn.fit(X_train_scale, y_train)

print('best_params:', knn.best_params_)
print('best_score:', knn.best_score_)

best_model_knn = knn.best_estimator_
pred_knn = best_model_knn.predict(X_test_scale)
print(classification_report(y_test, pred_knn))

best_params: {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'}
best_score: 0.875
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        48
           1       1.00      0.17      0.29        12

    accuracy                           0.83        60
   macro avg       0.91      0.58      0.60        60
weighted avg       0.86      0.83      0.78        60

In [56]:
print(f'Train score: {rf.score(X_train, y_train): .4f}')
print(f'Test score: {rf.score(X_test, y_test): .4f}')

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Condition_0
- Condition_1
- Condition_10
- Condition_11
- Condition_2
- ...
Feature names seen at fit time, yet now missing:
- Condition
- Crewed or Uncrewed
- Wind Direction

In [ ]:
# TODO: 모델 만들고 성능 평가하기
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
################################
# 스케일링, 원핫??
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
RandomForestClassifier(random_state=42)

n_estimators [100, 200, 300]
max_depth 
min_samples_split
min_samples_leaf

LogisticRegression(solver = 'liblinear', random_state=42)

penalty ['l1', 'l2']
C [0.01 , 0.1, 1, 10, 100]

KNeighborsClassifier()

n_neighbors [3, 5, 7, 9, 11, 13, 15]
weights ['uniform', 'distance']
metric [ 'euclidean', 'manhattan', 'minkowski']

SVC(random_state=42)

gamma [0.001, 0.01 , 0.1, 1, 'scale']
C [0.1, 1, 10, 100]
kernel ['linear', 'poly', 'rbf','sigmoid']

In [ ]:
out = f'''
compare DT ,RF, LR
DT : {dt.score(X_test, y_test)}
RF : {rf.score(X_test, y_test)}
LR : {lr.score(X_test, y_test)}

DT confusion matrix : 
{classification_report(y_test, y_pred_dt)}

RF confusion matrix : 
{classification_report(y_test, y_pred_rf)}

LR confusion matrix : 
{classification_report(y_test, y_pred_lr)}
'''
print(out)

compare DT ,RF, LR
DT : 0.9833333333333332
RF : 0.9833333333333333
LR : 0.8666666666666667

DT confusion matrix :
              precision    recall  f1-score   support

           N       1.00      0.98      0.99        49
           Y       0.92      1.00      0.96        11

    accuracy                           0.98        60
   macro avg       0.96      0.99      0.97        60
weighted avg       0.98      0.98      0.98        60


RF confusion matrix :
              precision    recall  f1-score   support

           N       1.00      0.98      0.99        49
           Y       0.92      1.00      0.96        11

    accuracy                           0.98        60
   macro avg       0.96      0.99      0.97        60
weighted avg       0.98      0.98      0.98        60


LR confusion matrix :
              precision    recall  f1-score   support

           N       0.87      0.98      0.92        49
           Y       0.80      0.36      0.50        11

    accuracy                           0.87        60
   macro avg       0.84      0.67      0.71        60
weighted avg       0.86      0.87      0.85        60